networks:
  services:
    name: cluster
  cache:
    name: redis
volumes:
  postgres-data:
  redis:
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: booking-postgres
    user: postgres
    restart: unless-stopped
    networks:
      - services
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: bitnami/redis:7.0.11
    container_name: booking-redis
    user: root
    networks:
      - cache
    environment:
      REDIS_PASSWORD: bitnami
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis/data
